name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build:
    needs: setup
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            binary: morrobroom
            archive: macos-latest.zip
          - os: ubuntu-latest
            binary: morrobroom
            archive: ubuntu-latest.zip
          - os: windows-latest
            binary: morrobroom.exe
            archive: windows-latest.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: build
        run: cargo +nightly build --release

      - name: compress
        run: tar -acf ${{ matrix.archive }} -C ./target/release/ ${{ matrix.binary }}

      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.archive }}
